"""Fix is_active column in Role to be non-nullable

Revision ID: 5acd05ac5170
Revises: 7d4e33d02a1e
Create Date: 2025-07-09 04:21:30.919314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5acd05ac5170'
down_revision = '7d4e33d02a1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
    op.execute('UPDATE role SET is_active = 1 WHERE is_active IS NULL')



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
